version: '3.8'

services:
  web:
    build: .
    command: python manage.py run -h 0.0.0.0
    networks:
      - default
    volumes:
      - ./app:/usr/src/app/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  db:
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
