version: '3.8'

services:
  web:
    build: .
    restart: always
    depends_on:
      - db
    networks:
      - default
    environment:
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    volumes:
      - ./classified_ads_crud:/usr/src/app/app
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
  db:
    env_file:
      - ./.env.dev
    networks:
      - default
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    image: postgres:13-alpine
    ports:
      - 5432:5432
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
